### ISSUE TITLE
Some tests fail on Darwin PowerPC (147 passed / 18 failed)

### ISSUE THREAD

**Issue by barracuda156** [ngtcp2/ngtcp2#805]
```
Start testing: May 24 15:26 CST
----------------------------------------------------------
1/1 Testing: main
1/1 Test: main
Command: "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/build/tests/main"
Directory: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/build/tests
"main" start time: May 24 15:26 CST
Output:
----------------------------------------------------------


     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/


Suite: libngtcp2_TestSuite
  Test: pkt_decode_version_cid ...passed
  Test: pkt_decode_hd_long ...passed
  Test: pkt_decode_hd_short ...passed
  Test: pkt_decode_stream_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:474  - 0xf1f2f3f4u == fr.stream.stream_id
    2. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:475  - 0x31f2f3f4f5f6f7f8llu == fr.stream.offset
  Test: pkt_decode_ack_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:551  - 0x31f2f3f4f5f6f7f8llu == fr.ack.largest_ack
    2. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:553  - 0x31e2e3e4e5e6e7e8llu == fr.ack.first_ack_range
    3. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:555  - 0x31d2d3d4d5d6d7d8llu == fr.ack.ranges[0].len
  Test: pkt_decode_padding_frame ...passed
  Test: pkt_encode_stream_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:603  - fr.stream.stream_id == nfr.stream.stream_id
    2. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:604  - fr.stream.offset == nfr.stream.offset
    3. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:664  - fr.stream.stream_id == nfr.stream.stream_id
    4. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:665  - fr.stream.offset == nfr.stream.offset
  Test: pkt_encode_ack_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:722  - fr->ack.largest_ack == nfr->ack.largest_ack
    2. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:750  - fr->ack.largest_ack == nfr->ack.largest_ack
    3. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:756  - fr->ack.ranges[i].len == nfr->ack.ranges[i].len
    4. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:756  - fr->ack.ranges[i].len == nfr->ack.ranges[i].len
  Test: pkt_encode_ack_ecn_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:791  - fr->ack.largest_ack == nfr->ack.largest_ack
    2. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:796  - fr->ack.ecn.ce == nfr->ack.ecn.ce
    3. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:825  - fr->ack.largest_ack == nfr->ack.largest_ack
    4. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:831  - fr->ack.ranges[i].len == nfr->ack.ranges[i].len
    5. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:831  - fr->ack.ranges[i].len == nfr->ack.ranges[i].len
  Test: pkt_encode_reset_stream_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:862  - fr.final_size == nfr.final_size
  Test: pkt_encode_connection_close_frame ...passed
  Test: pkt_encode_connection_close_app_frame ...passed
  Test: pkt_encode_max_data_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:978  - fr.max_data == nfr.max_data
  Test: pkt_encode_max_stream_data_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:999  - fr.stream_id == nfr.stream_id
    2. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:1000  - fr.max_stream_data == nfr.max_stream_data
  Test: pkt_encode_max_streams_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:1020  - fr.max_streams == nfr.max_streams
  Test: pkt_encode_ping_frame ...passed
  Test: pkt_encode_data_blocked_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:1060  - fr.offset == nfr.offset
  Test: pkt_encode_stream_data_blocked_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:1081  - fr.stream_id == nfr.stream_id
    2. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:1082  - fr.offset == nfr.offset
  Test: pkt_encode_streams_blocked_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:1102  - fr.max_streams == nfr.max_streams
  Test: pkt_encode_new_connection_id_frame ...passed
  Test: pkt_encode_stop_sending_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:1149  - fr.stream_id == nfr.stream_id
  Test: pkt_encode_path_challenge_frame ...passed
  Test: pkt_encode_path_response_frame ...passed
  Test: pkt_encode_crypto_frame ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_pkt_test.c:1222  - fr.crypto.offset == nfr.crypto.offset
  Test: pkt_encode_new_token_frame ...passed
  Test: pkt_encode_retire_connection_id ...passed
  Test: pkt_encode_handshake_done ...passed
  Test: pkt_encode_datagram_frame ...passed
  Test: pkt_adjust_pkt_num ...passed
  Test: pkt_validate_ack ...passed
  Test: pkt_write_stateless_reset ...passed
  Test: pkt_write_retry ...passed
  Test: pkt_write_version_negotiation ...passed
  Test: pkt_stream_max_datalen ...passed
  Test: get_varint ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_conv_test.c:116  - 1073741824 == n
    2. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_conv_test.c:127  - 4611686018427387903ULL == n
    3. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_conv_test.c:138  - 4611686018427387903LL == s
  Test: get_uvarintlen ...passed
  Test: put_uvarintlen ...passed
  Test: get_uint64 ...passed
  Test: get_uint48 ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_conv_test.c:225  - 123456789 == n
    2. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_conv_test.c:236  - 281474976710655ULL == n
  Test: get_uint32 ...passed
  Test: get_uint24 ...passed
  Test: get_uint16 ...passed
  Test: get_uint16be ...passed
  Test: nth_server_bidi_id ...passed
  Test: nth_server_uni_id ...passed
  Test: nth_client_bidi_id ...passed
  Test: nth_client_uni_id ...passed
  Test: range_intersect ...passed
  Test: range_cut ...passed
  Test: range_not_after ...passed
  Test: ksl_insert ...passed
  Test: ksl_clear ...passed
  Test: ksl_range ...passed
  Test: ksl_update_key_range ...passed
  Test: ksl_dup ...passed
  Test: ksl_remove_hint ...passed
  Test: rob_push ...passed
  Test: rob_push_random ...passed
  Test: rob_data_at ...passed
  Test: rob_remove_prefix ...passed
  Test: acktr_add ...passed
  Test: acktr_eviction ...passed
  Test: acktr_forget ...passed
  Test: acktr_recv_ack ...passed
  Test: transport_params_encode ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_crypto_test.c:218  - params.active_connection_id_limit == nparams.active_connection_id_limit
  Test: transport_params_decode_new ...FAILED
    1. /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_net_ngtcp2/ngtcp2/work/ngtcp2-0.15.0/tests/ngtcp2_crypto_test.c:397  - params.active_connection_id_limit == nparams->active_connection_id_limit
  Test: rtb_add ...passed
  Test: rtb_recv_ack ...passed
  Test: rtb_lost_pkt_ts ...passed
  Test: rtb_remove_expired_lost_pkt ...passed
  Test: rtb_remove_excessive_lost_pkt ...passed
  Test: idtr_open ...passed
  Test: ringbuf_push_front ...passed
  Test: ringbuf_pop_front ...passed
  Test: conn_stream_open_close ...passed
  Test: conn_stream_rx_flow_control ...passed
  Test: conn_stream_rx_flow_control_error ...passed
  Test: conn_stream_tx_flow_control ...passed
  Test: conn_rx_flow_control ...passed
  Test: conn_rx_flow_control_error ...passed
  Test: conn_tx_flow_control ...passed
  Test: conn_shutdown_stream_write ...passed
  Test: conn_recv_reset_stream ...passed
  Test: conn_recv_stop_sending ...passed
  Test: conn_recv_conn_id_omitted ...passed
  Test: conn_short_pkt_type ...passed
  Test: conn_recv_stateless_reset ...passed
  Test: conn_recv_retry ...passed
  Test: conn_recv_delayed_handshake_pkt ...passed
  Test: conn_recv_max_streams ...passed
  Test: conn_handshake ...passed
  Test: conn_handshake_error ...passed
  Test: conn_retransmit_protected ...passed
  Test: conn_send_max_stream_data ...passed
  Test: conn_recv_stream_data ...passed
  Test: conn_recv_ping ...passed
  Test: conn_recv_max_stream_data ...passed
  Test: conn_send_early_data ...passed
  Test: conn_recv_early_data ...passed
  Test: conn_recv_compound_pkt ...passed
  Test: conn_pkt_payloadlen ...passed
  Test: conn_writev_stream ...passed
  Test: conn_writev_datagram ...passed
  Test: conn_recv_datagram ...passed
  Test: conn_recv_new_connection_id ...passed
  Test: conn_recv_retire_connection_id ...passed
  Test: conn_server_path_validation ...passed
  Test: conn_client_connection_migration ...passed
  Test: conn_recv_path_challenge ...passed
  Test: conn_key_update ...passed
  Test: conn_crypto_buffer_exceeded ...passed
  Test: conn_handshake_probe ...passed
  Test: conn_handshake_loss ...passed
  Test: conn_probe ...passed
  Test: conn_recv_client_initial_retry ...passed
  Test: conn_recv_client_initial_token ...passed
  Test: conn_get_active_dcid ...passed
  Test: conn_recv_version_negotiation ...passed
  Test: conn_send_initial_token ...passed
  Test: conn_set_remote_transport_params ...passed
  Test: conn_write_connection_close ...passed
  Test: conn_write_application_close ...passed
  Test: conn_rtb_reclaim_on_pto ...passed
  Test: conn_rtb_reclaim_on_pto_datagram ...passed
  Test: conn_validate_ecn ...passed
  Test: conn_path_validation ...passed
  Test: conn_early_data_sync_stream_data_limit ...passed
  Test: conn_early_data_rejected ...passed
  Test: conn_keep_alive ...passed
  Test: conn_retire_stale_bound_dcid ...passed
  Test: conn_get_scid ...passed
  Test: conn_stream_close ...passed
  Test: conn_buffer_pkt ...passed
  Test: conn_handshake_timeout ...passed
  Test: conn_get_ccerr ...passed
  Test: conn_version_negotiation ...passed
  Test: conn_server_negotiate_version ...passed
  Test: conn_pmtud_loss ...passed
  Test: conn_amplification ...passed
  Test: conn_encode_early_transport_params ...passed
  Test: conn_new_failmalloc ...passed
  Test: accept ...passed
  Test: select_version ...passed
  Test: pkt_write_connection_close ...passed
  Test: map ...passed
  Test: map_functional ...passed
  Test: map_each_free ...passed
  Test: map_clear ...passed
  Test: gaptr_push ...passed
  Test: gaptr_is_pushed ...passed
  Test: gaptr_drop_first_gap ...passed
  Test: vec_split ...passed
  Test: vec_merge ...passed
  Test: vec_len_varint ...passed
  Test: strm_streamfrq_pop ...passed
  Test: strm_streamfrq_unacked_offset ...passed
  Test: strm_streamfrq_unacked_pop ...passed
  Test: pv_add_entry ...passed
  Test: pv_validate ...passed
  Test: pmtud_probe ...passed
  Test: encode_ipv4 ...passed
  Test: encode_ipv6 ...passed
  Test: get_bytes ...passed
  Test: transport_params_convert_to_latest ...passed
  Test: transport_params_convert_to_old ...passed

Run Summary:    Type   Total     Ran  Passed Failed Inactive
              suites       1       1     n/a      0        0
               tests     165     165     147     18        0
             asserts 2751723 2751723 2751687     36      n/a

Elapsed time =    1.008 seconds
<end of output>
Test time =   1.05 sec
----------------------------------------------------------
Test Failed.
"main" end time: May 24 15:26 CST
"main" time elapsed: 00:00:01
----------------------------------------------------------

End testing: May 24 15:26 CST
```

Could we fix these?
